# Generated by Django 2.1.5 on 2019-03-01 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20190301_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='comments',
            new_name='foods',
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Breed must be greater than 1 character')]),
        ),
    ]
